name: Create nightly release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compress Directories
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r intersect_training_data.zip ./intersect_training

      - name: Create Release
        uses: meeDamian/github-release@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: Master
          allow_override: True
          prerelease: True
          gzip: False
          files: >
            intersect_training_data.zip
