name: Create Release
on:
  push:
    tags: "*"

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r intersect_training.zip data results src docs README

      - name: Create Release
        uses: meeDamian/github-release@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: True
          gzip: False
          files: >
            intersect_training/intersect_training.zip
