name: Zip directories

on:
  push:
    tags: "*"

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        uses: meeDamian/github-release@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: True 
          files: >
            intersect-training-data.zip:intersect_training
        
